    <div class="left">
      <a href="http://gsoc.cat-v.org">gsoc</a> |
      <a href="http://doc.cat-v.org">doc archive</a> |
      <a href="http://repo.cat-v.org">software repo</a> |
      <a href="http://ninetimes.cat-v.org">ninetimes</a> |
      <a href="http://harmful.cat-v.org">harmful</a> |
      <a href="http://9p.cat-v.org/">9P</a> |
      <a href="http://cat-v.org">cat-v.org</a>
    </div>

    <div class="right">
      <span class="doNotDisplay">Related sites:</span>
      | <a href="http://cat-v.org/update_log">site updates</a>
      | <a href="/sitemap">site map</a>
    </div>

