<div class="left">
	<a href="http://kbct.de">kbct.de</a>
	<a href="http://blog.kbct.de">blog</a>
	<a href="http://media.kbct.de">media</a>
	<a href="http://bonzai.kbct.de">bonzai</a>
	<a>|</a>
	<a href="http://twitter.com/Knorkebrot">twitter</a>
	<a href="http://www.lastfm.de/user/Killerkasper">lastfm</a>
</div>

<div class="right">
	<a href="http://kbct.de/impressum">impressum</a>
	<a href="/sitemap">site map</a>
</div>
